### ISSUE TITLE
implement HTTP(S) proxy support

### ISSUE THREAD

**Issue by hellt** [mysocketio/mysocketctl-go#5]
Hi, thanks for this awesome project
please consider this as a Feature Request to add support for HTTP proxy config.
A lot of corporate lab networks are behind the HTTP(S) proxy, it would be nice if the client will respect the env vars HTTP_PROXY and HTTPS_PROXY when establishes connection towards api.mysocket.io

**Comment by atoonk** [comment]
thanks for the kind words @hellt 
I just did a quick test and it seems the Go libraries do the right thing already. 
This was the test:

```
export HTTP_PROXY=1.1.1.2:1234
mysocketctl socket ls
```
This times out since there's nothing listening on 1.1.1.2:1234
TCPdump shows it is indeed trying to talk to  1.1.1.2:1234

```
07:05:08.997985 IP 192.168.4.30.64420 > 1.1.1.2.1234: Flags [S], seq 4236855717, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2720782991 ecr 0,sackOK,eol], length 0
```

If we try something that has a webserver
```
export HTTP_PROXY=1.1.1.2:80
mysocketctl socket ls
2021/02/05 07:14:35 Error: Get "https://api.mysocket.io/connect": Bad Request

<tcpdump>
07:14:35.223350 IP 192.168.4.30.64588 > 1.1.1.2.80: Flags [P.], seq 1:100, ack 1, win 4096, length 99: HTTP: CONNECT api.mysocket.io:443 HTTP/1.1
```

So I can see it do the actual HTTP CONNECT to the HTTP_PROXY env. 
I don't have a proxy to test, but based on the above i think it should just work.

**Comment by atoonk** [comment]
Just to clarify, this is just for the API calls.
not the actual tunnel (ssh)
